### ISSUE TITLE
PECL ownership [discussion]

### ISSUE THREAD

**Issue by remicollet** [nano-interactive/cassandra-php-driver#30]
It looks like this fork exists since the original is not really maintained / active anymore

Is the new team willing to maintain it officially?

If yes, worth to raise the discussion on  pecl dev list (https://pecl.php.net/support.php#lists)

**Comment by malusev998** [comment]
We forked it when PHP 8.0 came out and made changes to support PHP 8.0.
After a few months I submitted a request to publish new cassandra driver under my account, but that would be in violation of my contract, and we as a team never had time to submit a proper request and discussion on PECL. 

I'm currently the only maintainer, and people started messaging me for the same request to publish it on PECL, but I do have a problem, even thou I make all of the calls to API changes, my team lead has to authorize all of the releases. I will speak with my team lead and have him answer your question about official maintenance.

Other problem here, V2(in development -> master branch) does not support PHP's build system, I have swapped it for CMake as it makes development easier (many of the IDEs support CMake) and it's quite hard to maintain two build systems, especially when one of them is poorly documented and no support for editors and IDEs.

If they give me enough of time to officially maintain the driver, with the help of the community, I would gladly do the maintenance of Cassandra Driver

**Comment by remicollet** [comment]
> does not support PHP's build system

Indeed this seems a blocker...
I also don't understand the need, nor the merged of lib (driver + libuv) into the sources... :(

**Comment by remicollet** [comment]
Also, any contact discussion with original author ?

ping @mikefero @adutra @mpenick

**Comment by remicollet** [comment]
Also, please update the README.md file about the status of this fork

**Comment by malusev998** [comment]
> Also, please update the README.md file about the status of this fork

I will when V2 becomes production ready and tests pass
There is a project board [https://github.com/nano-interactive/cassandra-php-driver/projects/1](https://github.com/nano-interactive/cassandra-php-driver/projects/1)
We try to keep it up to date on what needs to be done

**Comment by remicollet** [comment]
> We wanted to use latest version of libuv and add more async support

Please note this will be a blocker for most major Linux distribution ;)

**Comment by malusev998** [comment]
> > We wanted to use latest version of libuv and add more async support
> 
> Please note this will be a blocker for most major Linux distribution ;)

I think it will not be, we are statically linking it by default in V2, also cpp-driver is statically linked

**Comment by malusev998** [comment]
> Also, any contact discussion with original authors ?

Yes we tried, posted on Jira Issue tracker and nothing, nobody replied. 
I also personally tried to contact them on email and still no reply.
After that we forked it, make changes and didn't bother to send pull requests to the main repository, especially when nobody replied.

**Comment by malusev998** [comment]
We plan to maintain it as long as we use PHP in production, and that is for the foreseeable future. Any help from the community will be appreciated.
