### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by mikhainin** [nano-interactive/cassandra-php-driver#37]
Few questions about "contributing" rules.

Do we still require to sign DataStax's CLA? 

Is "[CONTRIBUTING.md](https://github.com/nano-interactive/ext-cassandra/blob/master/CONTRIBUTING.md)" still actual? 

I'm asking because our company is quite serious about contribution rules and if required, we will need to make some steps before entering into legally-binding relations (such as signing the Contribution License Agreement)

**Comment by CodeLieutenant** [comment]
For us its not required, only if you want to contribute back to DataStax, but since they are inactive and this is the only maintained fork we don't require the signing of CLA.
Only to follow the Apache 2.0 License. All contributions are welcome

**Comment by mikhainin** [comment]
Probably, it might be worth updating the contribution file :) 
Also, readme contains a note "The PHP driver is in maintenance mode" -- that's probably outdated as well :) 

Thanks for your answer anyways

**Comment by CodeLieutenant** [comment]
Currently I dont have time to maintain the driver, but will come back to it. Im the only one working on it in the company and I'm doing it mostly in my free time. It needs updating for a lot of stuff and a lot of fixes, hope I will find time in the near future to work on it

**Comment by CodeLieutenant** [comment]
Thanks for asking this very important question, I will pin this issue.
And of course, contributions are welcome, I dont have time to write the code but I will find time to review a pull request.
