### ISSUE TITLE
Support for PHP 7.4 or PHP 8?

### ISSUE THREAD

**Issue by binwiederhier** [nano-interactive/cassandra-php-driver#38]
Hi @malusev998, thanks for maintaining this driver. I couldn't get it to compile on Ubuntu 20.04 with PHP 7.4. Is PHP 7.4 supported?

**Comment by CodeLieutenant** [comment]
On master branch is not supported. for stable release check 1.3.x branch, works from 5.6 up to 8.2 (has support for 8.2 but its not tagged)

**Comment by binwiederhier** [comment]
Awesome. I'll try it Monday. Thanks for responding!

**Comment by binwiederhier** [comment]
Hurray. I built it on 7.4 :partying_face: -- I was too impatient to wait. Gonna see if it works Monday :-)
