### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by dada-amater** [nano-interactive/cassandra-php-driver#39]
Hey, guys,

First of all, thank you for your efforts and maintenance of the PHP Cassandra driver. Thanks to you, we have switched to PHP 8.0 and later to PHP 8.1.

Now PHP 8.2 is available, and I would like to ask you if you plan to upgrade the driver to the latest version.

Thank you.
David

**Comment by CodeLieutenant** [comment]
Driver already supports 8.2 in 1.3.x branch, but the release is not tagged. You can build it from there
