### ISSUE TITLE
Using a parameterised value for TTL throws an exception

### ISSUE THREAD

**Issue by downsider** [nano-interactive/cassandra-php-driver#4]
We appear to have found a bug when a TTL is set to a parameterised value

Running the following query and parameters causes the extension to throw the exception: `Cassandra\Exception\InvalidQueryException: Invalid amount of bind variables`

Query:
```
INSERT INTO myTable (
"field1",
"field2",
"field3
) VALUES (
:field1,
:field2,
:field3
) USING TTL :rowTtl;
```
Parameters:
```
[
    "field1": "value1",
    "field2": "value2",
    "field3": "value3",
    "rowTtl": 100
]
```

If the TTL clause is omitted or the rowTtl value is inserted directly into the query (e.g. `USING TTL 100;`) then the query works, just not when the value is a parameter

**Comment by malusev998** [comment]
I will look into it this week

**Comment by downsider** [comment]
Did anything come of this?

I rediscovered the "solution" I had to put in place, this week. It would be nice to move to fully parameterised queries :)

**Comment by CodeLieutenant** [comment]
I looked into it, in our codebase we are using TTL with prepared statement, but we are not using named parameters.

```
INSERT INTO myTable (field1,field2,field3) VALUES (?,?,?) USING TTL ?;
```

And this works fine.
Since V2 is on the way, we will refactor everything to fully parameterised queries and add full support for named params

**Comment by downsider** [comment]
Thanks for the clarification. Looking forward to V2 :)

**Comment by CodeLieutenant** [comment]
You can check the progres on master branch for v2
