### ISSUE TITLE
Improvements to Installation and project docs

### ISSUE THREAD

**Issue by danielhe4rt** [nano-interactive/cassandra-php-driver#40]
Hey! I'm opening this issue to discuss if there's anything else besides the project README and how to install the driver. 

Probably I'll be into the features, testing one by one soon but nothing that needs to be rushed for now.

**Comment by CodeLieutenant** [comment]
For now just README is enough, but in the future it would be nice to document how to setup a local development environment (build debug version of PHP, compile the driver and run tests, etc.).

And README in `ext` directory needs to be updated.
I think, some parts need to be completely removed, like building the extension on windows or mac, and building the extension should be explained on Ubuntu 22.02, for other distributions, it would be nice but that needs more testing (for now, others can be removed with, or left with TODO comments)

**Comment by CodeLieutenant** [comment]
Do you have any other suggestion?
