### ISSUE TITLE
Extension Testing

### ISSUE THREAD

**Issue by CodeLieutenant** [nano-interactive/cassandra-php-driver#43]
Currently tests are written with BDD style framework (behat), but this is not suitable for extension, There is certainly a better way, using PHPUnit or Pest, there are tests in PHPUnit but they are old and not working, needed to be rewriten.

**Comment by danielhe4rt** [comment]
I'll get some folks from He4rt to get it done, but first we'll need the Github Actions working properly and the environment to people easily write tests.

About which test framework use: maybe we can give Pest a try! I used once but I didn't get it so well to write good code. Maybe it's time to learn a whole new stack :p

**Comment by danielhe4rt** [comment]
Also maybe I can ping Nuno to give us some ideas after Laracon India is over.

**Comment by PedroPMS** [comment]
I'd like to help with this issue. But I don't have much experience with that cassandra and c++ environment. Could you indicate some tests that are friendly to start with?

**Comment by CodeLieutenant** [comment]
Ill be making a pull request soon, that setups Pest and first test, from there we can describe what needs to be tested and how

**Comment by danielhe4rt** [comment]
If possible, move all the current testing suites to a folder called "old" or something like that to us know exactly what we have to cover in a first moment.

**Comment by CodeLieutenant** [comment]
I though so too, just move old code and setup the new one, also we will need to see which tests would be good and necessary.

**Comment by CodeLieutenant** [comment]
@DanielHe4rt @PedroPMS I've created a pull request with simple test (from tests/feature).
If you would like to help, just say which test files you will rewrite, so we don't conflict with each other.

I'll finish `collections.feature` and start working on:

* [batch_statements.feature](https://github.com/he4rt/scylladb-php-driver/blob/v1.3.x/tests/features/batch_statements.feature)
* [client_side_timestamps.feature](https://github.com/he4rt/scylladb-php-driver/blob/v1.3.x/tests/features/client_side_timestamps.feature)
* [consistency_level.feature](https://github.com/he4rt/scylladb-php-driver/blob/v1.3.x/tests/features/consistency_level.feature)
* [duration.feature](https://github.com/he4rt/scylladb-php-driver/blob/v1.3.x/tests/features/duration.feature)
