### ISSUE TITLE
Running queries before the Keyspace

### ISSUE THREAD

**Issue by danielhe4rt** [nano-interactive/cassandra-php-driver#46]
Hey y'all!

I'm testing the driver after have a few weeks studying ScyllaDB and the environment and I probably didn't found anything related to that but: Can I execute a query before having a keyspace with the driver?

My scenario is: I want to run a "migration" command that also will create the Keyspace, but seems that I have to create it first and then run the migrations.

There's any reason to not have a "raw" connection to CQLSH and you prompt w/e you want?

**Comment by CodeLieutenant** [comment]
This will be allowed after the refactor

There is a way in current setup but puts warnings

```
$val = $cluster->connect(/* empty $keyspace */);
```

Since `$keyspace` is empty and stubs do not allow empty value for argument, this produces warnings.
