### ISSUE TITLE
withConnectionsPerHost() has "core" and "max" arguments mixed up

### ISSUE THREAD

**Issue by evll** [nano-interactive/cassandra-php-driver#64]
```php
Cassandra::cluster()->withConnectionsPerHost(1, 2)
```

gives "Cassandra\Exception\InvalidArgumentException: max must be greater than core, 2 given"

While 
```php
Cassandra::cluster()->withConnectionsPerHost(2, 1)
```

does not return such an error.

Function definition is `public function withConnectionsPerHost($core, $max) {}`, so the first variant should work correctly.

**Comment by evll** [comment]
This is also from 1.3.x branch

**Comment by CodeLieutenant** [comment]
Can you provide you PHP version?

**Comment by evll** [comment]
PHP 8.2.6
