### ISSUE TITLE
Missing information on build steps

### ISSUE THREAD

**Issue by danielhe4rt** [nano-interactive/cassandra-php-driver#69]
I was trying to build the driver again in my machine and got this message. Any clue of what is missing? 

![image](https://github.com/he4rt/scylladb-php-driver/assets/6912596/a70ba213-e07c-49e0-a2be-503e7a81df7f)

**Comment by CodeLieutenant** [comment]
Do a recusive clone on the repository as a git submodule, sanitizers have been added (Asan and Ubsan).

I'll update the documentation
