### ISSUE TITLE
clone error - "Please make sure you have the correct access rights and the repository exists."

### ISSUE THREAD

**Issue by ghnp5** [nano-interactive/cassandra-php-driver#76]
Hi,

I'm running this:

`git clone --recursive https://github.com/he4rt/scylladb-php-driver`

On Debian docker.

But I'm getting this issue:

> Cloning into 'scylladb-php-driver'...
Submodule 'third-party/sanitizers-cmake' (git@github.com:arsenm/sanitizers-cmake.git) registered for path 'third-party/sanitizers-cmake'
Cloning into '/scylladb-php-driver/third-party/sanitizers-cmake'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:arsenm/sanitizers-cmake.git' into submodule path '/scylladb-php-driver/third-party/sanitizers-cmake' failed
Failed to clone 'third-party/sanitizers-cmake'. Retry scheduled
Cloning into '/scylladb-php-driver/third-party/sanitizers-cmake'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:arsenm/sanitizers-cmake.git' into submodule path '/scylladb-php-driver/third-party/sanitizers-cmake' failed
Failed to clone 'third-party/sanitizers-cmake' a second time, aborting

Any ideas why?

**Comment by CodeLieutenant** [comment]
Can you provide more context, I couldn't replicate your issue anywhere
