### ISSUE TITLE
[ERROR] Fatal: The remote end hung up unexpectedly

### ISSUE THREAD

**Issue by iamrafaelmelo** [nano-interactive/cassandra-php-driver#77]
Is there a specific reason why the url of the `third-party/sanitizers-cmake` module in the `.gitmodules` file is for SSH and not HTTPS?

I ask this because I am not able to build the driver with Dockerfile, because when trying to clone the module, I get the error [Fatal Error when updating submodule](https://stackoverflow.com/questions/8197089/fatal-error-when-updating-submodule-using-git).

**Comment by CodeLieutenant** [comment]
There is no reason, just a mistake. I'll fix it. thanks for the report

**Comment by CodeLieutenant** [comment]
If it's urgent to you. You can make a pull request I'll be happy to review it and merge it quickly

**Comment by iamrafaelmelo** [comment]
> If it's urgent to you. You can make a pull request I'll be happy to review it and merge it quickly

Ok, i'm create PR: #78
