### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by dada-amater** [nano-interactive/cassandra-php-driver#8]
Hey, guys,

First of all, thank you for your efforts and maintenance of the PHP Cassandra driver. Thanks to you, we have switched to PHP 8.0.

Now PHP 8.1 is available and I would like to ask you if you are planning to upgrade the driver to the latest version.

Thank you.
David

**Comment by malusev998** [comment]
We already updated driver to 8.1 on php8.1 branch, but i do not consider it stable to be used in production, a lot of PHP 5 stuff is getting removed from the codebase

**Comment by malusev998** [comment]
#9 There is pull request for PHP 8.1

**Comment by dada-amater** [comment]
It seems PR #9 is stuck :-/

**Comment by malusev998** [comment]
No it's not, currently we don't have time to push it forwards. As soon as I have some spare time, it will be properly checked and merged

**Comment by malusev998** [comment]
We are still using PHP 8.0 in production, so there is no need for now to push 8.1, We are waiting on Ubuntu 22.04 LTS release

**Comment by dada-amater** [comment]
> We are still using PHP 8.0 in production, so there is no need for now to push 8.1, We are waiting on Ubuntu 22.04 LTS release

OK. We have an upgrade to PHP 8.1 ready, just the Cassandra driver is the only blocker :-/.

**Comment by malusev998** [comment]
If it's your only blocker, feel free to send pull request

**Comment by dada-amater** [comment]
> If it's your only blocker, feel free to send pull request

I would do it with pleasure, but unfortunately, I don't have the skills to do it.

**Comment by malusev998** [comment]
Version 1.3.6 supports PHP 8.1, but spits out deprecation warnings, which will be addressed in future version.
