### ISSUE TITLE
[ERROR] Undefined symbol: _Z8php_statP12_zend_stringiP12_zval_struct

### ISSUE THREAD

**Issue by iamrafaelmelo** [nano-interactive/cassandra-php-driver#80]
In an attempt to use SSL options using the methods (only one or all):
- `withTrustedCerts`
- `withClientCert`
- `withPrivateKey`

Passing or not parameters, this error is returned:
| Class | Error |
|:-----:|:-----:|
|![image](https://github.com/he4rt/scylladb-php-driver/assets/52138516/bdea8790-e6f6-424b-ab4a-7e980a974f4a) | ![image](https://github.com/he4rt/scylladb-php-driver/assets/52138516/4cf4f7fb-629b-4fb1-aabc-8687d449e6a6) |

**Comment by CodeLieutenant** [comment]
Should be fixed in [54a2c93](https://github.com/he4rt/scylladb-php-driver/commit/54a2c936c88be954a1add4c6fd9ce1457d8b5ec4)

I'll be closing it now, free feel to reopen it if you still encounter the same error.
