### ISSUE TITLE
Php 8.2 issue

### ISSUE THREAD

**Issue by arkadicolson** [nano-interactive/cassandra-php-driver#88]
Hi

After building the module I'm getting these messages when running php with cassandra class loaded. I followed the guide to build the scyladb-driver driver as well as the php module. Buils succeeded but got the error below in the syslog. Any idea what could be wrong here? 

Nov  7 10:54:55 staginga kernel: [2341210.148844] traps: php[4194285] general protection fault ip:55f769f88cc4 sp:7fff240d5c58 error:0 in php8.2[55f769da9000+2fb000]

**Comment by CodeLieutenant** [comment]
Can you provide some more information. This is not enough

**Comment by arkadicolson** [comment]
Hi

I started over again and came to this problem now:

`
root@staginga:/opt/cassandra-build/scylladb-php-driver# /usr/local/lib/python3.9/dist-packages/cmake/data/bin/cmake -DCASS_CPP_STANDARD=17 -DCASS_BUILD_STATIC=ON -DCASS_BUILD_SHARED=ON -DCASS_USE_STD_ATOMIC=ON -DCASS_USE_TIMERFD=ON -DCASS_USE_LIBSSH2=ON -DCASS_USE_ZLIB=ON CMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC -Wno-error=redundant-move" -DCMAKE_BUILD_TYPE="ReleaseLibCassandra" -G Ninja .. 
CMake Warning:
  Ignoring extra path from command line:

   "/opt/cassandra-build/scyladb-driver/build/CMAKE_C_FLAGS=-fPIC"


CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- libuv version: v1.40.0
-- Found Libuv: /usr/lib/x86_64-linux-gnu/libuv.so (found suitable version "1.40.0", minimum required is "1.0.0") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so (found version "1.1.1w") 
-- OpenSSL version: v1.1.1w
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")  
CMake Deprecation Warning at cmake/ClangFormat.cmake:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  CMakeLists.txt:87 (include)


-- Could NOT find CLANG_FORMAT (missing: CLANG_FORMAT_EXE) 
-- Unable to find clang-format. Not creating format targets.
-- Driver version: 2.16.2
-- Using std::atomic implementation for atomic operations
-- Using std::optional library
CMake Deprecation Warning at src/third_party/sparsehash/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Checking to see if CXX compiler accepts flag -std=c++11
-- Checking to see if CXX compiler accepts flag -std=c++11 - yes
-- Using hash header <functional> and namespace "std"
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for memcpy
-- Looking for memcpy - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long long
-- Check size of long long - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of u_int16_t
-- Check size of u_int16_t - done
-- Check size of __uint16_t
-- Check size of __uint16_t - done
-- Looking for GRND_NONBLOCK
-- Looking for GRND_NONBLOCK - found
-- Looking for timerfd_create
-- Looking for timerfd_create - found
-- Looking for SO_NOSIGPIPE
-- Looking for SO_NOSIGPIPE - not found
-- Looking for sigtimedwait
-- Looking for sigtimedwait - found
-- Performing Test HAVE_BUILTIN_BSWAP32
-- Performing Test HAVE_BUILTIN_BSWAP32 - Success
-- Performing Test HAVE_BUILTIN_BSWAP64
-- Performing Test HAVE_BUILTIN_BSWAP64 - Failed
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Configuring done (1.9s)
-- Generating done (0.0s)
-- Build files have been written to: /opt/cassandra-build/scyladb-driver/build

root@staginga:/opt/cassandra-build/scyladb-driver/build# ninja install
[257/258] Install the project...
-- Install configuration: "ReleaseLibCassandra"
-- Installing: /usr/local/include/cassandra.h
-- Installing: /usr/local/include/dse.h
-- Installing: /usr/local/lib/x86_64-linux-gnu/libscylla-cpp-driver.so.2.16.2
-- Installing: /usr/local/lib/x86_64-linux-gnu/libscylla-cpp-driver.so.2
-- Installing: /usr/local/lib/x86_64-linux-gnu/libscylla-cpp-driver.so
-- Installing: /usr/local/lib/x86_64-linux-gnu/pkgconfig/scylla-cpp-driver.pc
-- Installing: /usr/local/lib/x86_64-linux-gnu/libscylla-cpp-driver_static.a
-- Installing: /usr/local/lib/x86_64-linux-gnu/pkgconfig/scylla-cpp-driver_static.pc
`
`
root@staginga:/opt/cassandra-build/scylladb-php-driver# /usr/local/lib/python3.9/dist-packages/cmake/data/bin/cmake  --preset ReleaseLibCassandra
Preset CMake variables:

  CMAKE_BUILD_TYPE="Release"
  CMAKE_INSTALL_PREFIX="/opt/cassandra-build/scylladb-php-driver/out/install/ReleaseLibCassandra"
  PHP_SCYLLADB_USE_LIBCASSANDRA="ON"
  SANITIZE_ADDRESS="OFF"
  SANITIZE_UNDEFINED="OFF"

-- Searching php-config PHP-VERSION: 8.2
-- Found php-config: /usr/bin/php-config
-- Checking for module 'cassandra'
--   No package 'cassandra' found
CMake Error at /usr/local/lib/python3.9/dist-packages/cmake/data/share/cmake-3.27/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/lib/python3.9/dist-packages/cmake/data/share/cmake-3.27/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  cmake/FindCassandraDriver.cmake:57 (pkg_check_modules)
  CMakeLists.txt:56 (find_package)


-- Configuring incomplete, errors occurred!
`

It cannot find the cassandra lib. Any idea why?

**Comment by CodeLieutenant** [comment]
Have you built the cpp-driver from source?

**Comment by CodeLieutenant** [comment]
If you are doing this in docker, there is a bug in php docker images

```
ENV LD_LIBRARY_PATH="/lib/x86_64-linux-gnu/:/usr/local/lib/:/usr/lib:/lib:/lib64"
```

You can try and add this to your dockerfile, fixed our build

**Comment by arkadicolson** [comment]
Never mind. Problem found... We are still using cassandra version 2.x and should be at least 3.x
Thx for your time!
