### ISSUE TITLE
When compiled version of extension

### ISSUE THREAD

**Issue by faustynm** [nano-interactive/cassandra-php-driver#98]
On main page:
_Binary versions of the driver, available for Linux systems and officialy supported versions of PHP (8.1 and 8.2), can be obtained from GitHub Releases (soon)._

I started a new project, I would like to use scylladb. I have a problem compiling the extension. When to expect compiled extensions to be available

**Comment by CodeLieutenant** [comment]
It will be always better for you to compile it, as binary distributions will only work for the platforms where it was built, (Ubuntu 22.04 binary will have no guarantee that the same binary will work on 24.04, dynamic linking problem). Depending on what are your needs, you can just use this script as an example of how to build the driver from the source

Make sure you have all the correct dependencies for your system (Mac/Linux)

- libgmp
- libuv
- libz
- libcurl
- libscylladb (By default it will be built from source in the following example on the latest TAG, if you need Apache Cassandra support, check the CMake file for the options - I'll make sure to document them in the future)

```sh
cmake --preset Release
pushd out/Release
ninja install

# Put this into cassandra.ini in your php ini directory
extension=cassandra
```

**Comment by faustynm** [comment]
THX

In example In QuickStart is error:
$result    = $querySent->get(); 

I received:
Fatal error: Uncaught Error: Call to undefined method Cassandra\Rows::get() in .....

I had to change to:
$result    = $querySent->offsetGet(0);

**Comment by CodeLieutenant** [comment]
this looks like a bug, will fix it, thanks

**Comment by Daniel-Boll** [comment]
Hey @CodeLieutenant isn't possible to bake the dependencies into the compiled versions with a static link approach? I have tried similar things to C++ native packages with patchelf in the node package environment.

**Comment by CodeLieutenant** [comment]
> Hey @CodeLieutenant isn't possible to bake the dependencies into the compiled versions with a static link approach? I have tried similar things to C++ native packages with patchelf in the node package environment.

Yes, you can, there are CMake flags for That

```sh
cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithInfo -DPHP_SCYLLADB_LIBUV_STATIC=ON -DPHP_SCYLLADB_LIBUV_FROM_SRC=ON -DPHP_SCYLLADB_LIBSCYLLADB_STATIC=ON -DPHP_SCYLLADB_LIBSCYLLADB_FROM_SRC=ON
```

If you want to use `LibCassandra` instead of `LibScyllaDB` just add `-DPHP_SCYLLADB_USE_LIBCASSANDRA=ON`

This will link `libuv` and `lib(scylla/cassandra)` statically, but glibc will be dynamic linking. I don't like static linking, if you are doing it, have good reason

**Comment by Daniel-Boll** [comment]
Oh, great! Isn't this enough to allow some platform support in the release package then? I mean, having libscylla or libcassandra statically linked already is a great way to decrease the platform specific problems.

**Comment by CodeLieutenant** [comment]
> Oh, great! Isn't this enough to allow some platform support in the release package then? I mean, having libscylla or libcassandra statically linked already is a great way to decrease the platform specific problems.

What platform issues, this package does not have many external deps, libuv and libcassandra/libscylladb, glibc and openssl, libgmp and all of those are in Distro repos, except libcassandra/libscylladb, which we are providing from source, static or dynamic linking.
I've tested this extension on Ubuntu, Fedora, CentOS, Arch Linux and I'm developing on Mac (also compiles without any problems). You can run in the release build without any issues.

I would never link openssl statically, it's too much of a risk, that also goes for GLibC which are 2 main components.

Windows is not supported, and I don't think it will ever be (unless someone steps up and does the support, I'm not windows expert, PHP runs on Linux Servers mostly. If someone is running it on Windows Server, good luck.
